import foto from "../src/assets/28.jpg";

export const dataSource = [
  {
    key: "2",
    guid: 21,
    user_foto: foto,
    user_name: "test1",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "Отклоненные",
    status: "Отказано",
  },
  {
    key: "3",
    guid: 22,
    user_foto: foto,
    user_name: "test2",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "В процессе",
    status: "На обработке",
  },
  {
    key: "4",
    guid: 22,
    user_foto: foto,
    user_name: "test3",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "Черновики",
    status: "Черновик",
  },
  {
    key: "5",
    guid: 24,
    user_foto: foto,
    user_name: "test4",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "На доработке",
    status: "Доработать",
  },
  {
    key: "6",
    guid: 25,
    user_foto: foto,
    user_name: "test5",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "Черновики",
    status: "Черновик",
  },
  {
    key: "7",
    guid: 26,
    user_foto: foto,
    user_name: "test6",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "Черновики",
    status: "Черновик",
  },
  {
    key: "8",
    guid: 27,
    user_foto: foto,
    user_name: "test7",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "Черновики",
    status: "Черновик",
  },
  {
    key: "9",
    guid: 27,
    user_foto: foto,
    user_name: "test8",
    title: "qwerty",
    date: "2025-01-01",
    folder_name: "Черновики",
    status: "Черновик",
  },
];
